src/FA.JustBlog/FA.JustBlog.WebMVC/Areas/Admin/Controllers/TagManagementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using FA.JustBlog.Data;
using FA.JustBlog.Models.Common;
using FA.JustBlog.Services;
using FA.JustBlog.WebMVC.Areas.Admin.ViewModels;

namespace FA.JustBlog.WebMVC.Areas.Admin.Controllers
{
    [Authorize]
    public class TagManagementController : Controller
    {
        private readonly ITagService _tagServices;

        public TagManagementController(ITagService tagServices)
        {
            _tagServices = tagServices;
        }

        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string searchString,
             int? pageIndex = 1, int pageSize = 2)
        {
            ViewData["CurrentPageSize"] = pageSize;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["UrlSlugSortParm"] = sortOrder == "UrlSlug" ? "urlSlug_desc" : "UrlSlug";
            ViewData["TotalPostsSortParm"] = sortOrder == "TotalPosts" ? "totalPosts_desc" : "TotalPosts";
            ViewData["InsertedAtSortParm"] = sortOrder == "InsertedAt" ? "insertedAt_desc" : "InsertedAt";
            ViewData["UpdatedAtSortParm"] = sortOrder == "UpdatedAt" ? "updatedAt_desc" : "UpdatedAt";

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            // x => x.Name.Contains(searchString)
            Expression<Func<Tag, bool>> filter = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = c => c.Name.Contains(searchString);
            }

            // q => q.OrderByDescending(c => c.Name)
            Func<IQueryable<Tag>, IOrderedQueryable<Tag>> orderBy = null;

            switch (sortOrder)
            {
                case "name_desc":
                    orderBy = q => q.OrderByDescending(c => c.Name);
                    break;
                case "UrlSlug":
                    orderBy = q => q.OrderBy(c => c.UrlSlug);
                    break;
                case "urlSlug_desc":
                    orderBy = q => q.OrderByDescending(c => c.UrlSlug);
                    break;
                case "TotalPosts":
                    orderBy = q => q.OrderBy(c => c.Posts.Count);
                    break;
                case "totalPosts_desc":
                    orderBy = q => q.OrderByDescending(c => c.Posts.Count);
                    break;
                case "InsertedAt":
                    orderBy = q => q.OrderBy(c => c.InsertedAt);
                    break;
                case "insertedAt_desc":
                    orderBy = q => q.OrderByDescending(c => c.InsertedAt);
                    break;
                case "UpdatedAt":
                    orderBy = q => q.OrderBy(c => c.UpdatedAt);
                    break;
                case "updatedAt_desc":
                    orderBy = q => q.OrderByDescending(c => c.UpdatedAt);
                    break;
                default:
                    orderBy = q => q.OrderBy(c => c.Name);
                    break;
            }

            var tags = await _tagServices.GetAsync(filter: filter, orderBy: orderBy, pageIndex: pageIndex ?? 1, pageSize: pageSize);

            return View(tags);
        }

        // GET: Admin/TagManagement/Create
        public ActionResult Create()
        {
            var tagViewModel = new TagViewModel();
            return View(tagViewModel);
        }

        // POST: Admin/TagManagement/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult Create(TagViewModel tagViewModel)
        {
            if (ModelState.IsValid)
            {
                var tag = new Tag
                {
                    Id = Guid.NewGuid(),
                    Name = tagViewModel.Name,
                    UrlSlug = tagViewModel.UrlSlug,
                    Description = tagViewModel.Description,
                };
                var result = _tagServices.Add(tag);
                if (result > 0)
                {
                    TempData["Message"] = "Create tag successful!";
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Message = "Create tag failed! Please try again!";
                }
            }

            return View(tagViewModel);
        }

        // GET: Admin/CategoryManagement/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var tag = _tagServices.GetById((Guid)id);
            if (tag == null)
            {
                return HttpNotFound();
            }

            var tagViewModel = new TagViewModel()
            {
                Id = tag.Id,
                Name = tag.Name,
                UrlSlug = tag.UrlSlug,
                Description = tag.Description
            };
            return View(tagViewModel);
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(TagViewModel tagViewModel)
        {
            if (ModelState.IsValid)
            {
                var tag = await _tagServices.GetByIdAsync(tagViewModel.Id);
                if (tag == null)
                {
                    return HttpNotFound();
                }
                tag.Name = tagViewModel.Name;
                tag.UrlSlug = tagViewModel.UrlSlug;
                tag.Description = tagViewModel.Description;

                _tagServices.Update(tag);
                return RedirectToAction("Index");
            }
            return View(tagViewModel);
        }


        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(Guid id)
        {
            var tag = _tagServices.GetById(id);
            var result = _tagServices.Delete(tag.Id);
            if (result)
            {
                TempData["Message"] = "Delete Successful";
            }
            else
            {
                TempData["Message"] = "Delete Failed";
            }
            return RedirectToAction("Index");
        }
    }
}

src/FA.JustBlog/FA.JustBlog.WebMVC/Areas/Admin/Views/TagManagement/Create.cshtml
@model TagViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create Tag</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="col-md-12">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", id = "input-title" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control", @readonly = true, id = "input-urlslug" } })
                @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
            <div class="">
                <textarea class="form-control" name="Description" id="ckeditor"></textarea>
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-12 row">
            <button type="submit" class="btn btn-info">
                Create
            </button>
            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}


@section scripts {
    <script src="~/Assets/js/ckeditor/ckeditor.js"></script>
    <script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
    <script src="~/assets/js/convert-urlslug.js"></script>
} 

src/FA.JustBlog/FA.JustBlog.WebMVC/Areas/Admin/Views/TagManagement/Edit.cshtml
@model TagViewModel

@{
    ViewBag.Title = "Edit: " + Model.Name;
}

<h2>Edit Category: @Model.Name</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.Id)
    <div class="row">
        <div class="col-md-12">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", id = "input-title" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control", @readonly = true, id = "input-urlslug" } })
                @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label" })
            <div class="">
                <textarea class="form-control" name="Description" id="ckeditor">@Model.Description</textarea>
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-12 row">
            <button type="submit" class="btn btn-info">
                Edit
            </button>
            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}


@section scripts {
    <script src="~/Assets/js/ckeditor/ckeditor.js"></script>
    <script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
    <script src="~/assets/js/convert-urlslug.js"></script>
} 

src/FA.JustBlog/FA.JustBlog.WebMVC/Areas/Admin/Views/TagManagement/Index.cshtml
@model Paginated<Tag>

@{
    ViewBag.Title = "Tag Management";
}

<h2 class="text-center">Tag Management</h2>
<h3>@TempData["Message"]</h3>
<hr />
<div>
    <a href="@Url.Action("Create", "TagManagement")" class="btn btn-primary float-left"><span class="fas fa-plus-square"></span></a>

    <form action="@Url.Action("Index", "TagManagement")" method="get" class="form-inline float-right">
        <div class="form-group mx-sm-3 mb-2">
            <input type="text" class="form-control mr-3" id="inputSearch" name="SearchString" value="@ViewData["currentFilter"]" placeholder="Input....">
            <button type="submit" class=" form-control btn btn-primary">
                <i class="fas fa-search"></i>
            </button>
            <a href="@Url.Action("Index")" class="btn btn-default">
                <i class="fas fa-redo"></i>
            </a>
        </div>
    </form>
</div>

@if (!Model.Any())
{
    <h3 class="text-center">Don't have a category yet.</h3>
}
else
{
    <table class="table table-condensed table-bordered">
        <tr class="d-flex">
            <th class="col-md-2">
                <a href="@Url.Action("Index", "TagManagement", new { sortOrder = ViewData["NameSortParm"], currentFilter = ViewData["CurrentFilter"] })">Name</a>
            </th>
            <th class="col-md-2">
                <a href="@Url.Action("Index", "TagManagement", new { sortOrder = ViewData["UrlSlugSortParm"], currentFilter = ViewData["CurrentFilter"] })">Url Slug</a>
            </th>
            <th class="col-md-2">
                <a href="@Url.Action("Index", "TagManagement", new { sortOrder = ViewData["TotalPostsSortParm"], currentFilter = ViewData["CurrentFilter"] })">Total Posts</a>
            </th>
            <th class="col-md-2">
                <a href="@Url.Action("Index", "TagManagement", new { sortOrder = ViewData["InsertedAtSortParm"], currentFilter = ViewData["CurrentFilter"] })">Inserted At</a>
            </th>
            <th class="col-md-2">
                <a href="@Url.Action("Index", "TagManagement", new { sortOrder = ViewData["UpdatedAtSortParm"], currentFilter = ViewData["CurrentFilter"] })">Updated At</a>
            </th>
            <th class="col-md-2">Manage</th>
        </tr>

        @foreach (var category in Model)
        {
            <tr class="d-flex">
                <td class="col-md-2">
                    <a href="@Url.Action("Details", new { id = category.Id})">
                        @category.Name
                    </a>
                </td>
                <td class="col-md-2">
                    @category.UrlSlug
                </td>
                <td class="col-md-2">
                    @Html.Raw(category.Posts.Count)
                </td>
                <td class="col-md-2">
                    @category.InsertedAt
                </td>
                <td class="col-md-2">
                    @category.UpdatedAt
                </td>
                <td class="col-md-2">
                    <form action="@Url.Action("Delete", "TagManagement", new{ id = category.Id })" method="post">
                        <a href="@Url.Action("Edit", "TagManagement", new { id = category.Id})" class="btn btn-primary">Edit</a>
                        <button type="submit" onclick="return confirm('Are you sure to delete this category?');" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </table>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                ViewBag.PageRange = 3;
            }
            <li class="page-item">
                <a href="@Url.Action("Index", "TagManagement", new { sortOrder=ViewData["CurrentSort"], pageIndex=1, currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @prevDisabled"><<</a>
            <li class="page-item">
                <a href="@Url.Action("Index", "TagManagement", new { sortOrder=ViewData["CurrentSort"], pageIndex=(Model.PageIndex - 1 <= 0 ? 1 : Model.PageIndex - 1), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @prevDisabled"><</a>
            </li>
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                if (i >= Model.PageIndex - ViewBag.PageRange && i <= Model.PageIndex + ViewBag.PageRange)
                {
                    <li class="page-item">
                        <a class="@(i==Model.PageIndex ? "Current" : "") page-link"
                           href="@Url.Action("Index", "TagManagement", new { sortOrder=ViewData["CurrentSort"], pageIndex=i, currentFilter=ViewData["CurrentFilter"] })">@i</a>
                    </li>
                }
            }
            <li class="page-item">
                <a href="@Url.Action("Index", "TagManagement", new { sortOrder=ViewData["CurrentSort"], pageIndex=(Model.PageIndex + 1 > Model.TotalPages ? Model.TotalPages : Model.PageIndex + 1), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @nextDisabled">></a>
            <li class="page-item">
                <a href="@Url.Action("Index", "TagManagement", new { sortOrder=ViewData["CurrentSort"], pageIndex=(Model.TotalPages), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @nextDisabled">>></a>
        </ul>
    </nav>
}