src/FA.JustBlog/FA.JustBlog.WebMVC/Areas/Identity/Controllers/UserAdminController.cs
using FA.JustBlog.Models.Security;
using FA.JustBlog.WebMVC.Areas.Identity.ViewModels;
using FA.JustBlog.WebMVC.ViewModels;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FA.JustBlog.WebMVC.Areas.Identity.Controllers
{
    [Authorize(Roles = "Admin")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new User { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                })
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;

                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

src/FA.JustBlog/FA.JustBlog.WebMVC/Controllers/CategoriesController.cs
using FA.JustBlog.Services;
using FA.JustBlog.WebMVC.ViewModels;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FA.JustBlog.WebMVC.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly IPostService _postServices;
        private readonly ICategoryService _categoryServices;

        public CategoriesController(IPostService postServices, ICategoryService categoryServices)
        {
            _postServices = postServices;
            _categoryServices = categoryServices;
        }

        public async Task<ActionResult> Details(string urlSlug)
        {
            var category = await _categoryServices.GetCategoryByUrlSlugAsync(urlSlug);
            if (category == null)
            {
                return HttpNotFound();
            }
            var posts = await _postServices.GetPostsByCategoryAsync(category.Id);
            return View(posts);
        }
        public ActionResult CategoryRightMenu()
        {
            var categoriesRightMenuViewModel = _categoryServices.GetAll().Select(x => new CategoryRightMenuViewModel
            {
                Id = x.Id,
                Name = x.Name,
                PostCount = x.Posts.Count,
                UrlSlug = x.UrlSlug

            }).OrderByDescending(c => c.PostCount);
            return PartialView("_CategoryRightMenu", categoriesRightMenuViewModel);
        }
    }
}

src/FA.JustBlog/FA.JustBlog.WebMVC/Controllers/PostsController.cs
using FA.JustBlog.Models.Common;
using FA.JustBlog.Services;
using FA.JustBlog.WebMVC.Areas.Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FA.JustBlog.WebMVC.Controllers
{
    public class PostsController : Controller
    {
        private readonly IPostService _postService;
        private readonly ICategoryService _categoryService;
        private readonly ICommentService _commentService;

        //private readonly PostsController : Controller;
        public PostsController(IPostService postService, ICategoryService categoryService, ICommentService commentService)
        {
            _commentService = commentService;
            _postService = postService;
            _categoryService = categoryService;
        }
        
        // GET: Posts
        public async Task<ActionResult> Index()
        {
            var allPosts = await _postService.GetAllAsync();
            return View(allPosts);
        }

        public ActionResult LastestPosts()
        {
            var lastestPosts = Task.Run(() => _postService.GetLatestPostAsync(5)).Result;
            ViewBag.PartialViewTitle = "Lastest Posts";
            return PartialView("_ListPost", lastestPosts);
        }

        public ActionResult MostViewPosts()
        {
            var lastestPosts = Task.Run(() => _postService.GetMostViewPostsAsync(5)).Result;
            ViewBag.PartialViewTitle = "Most View Posts";
            return PartialView("_PopularPosts", lastestPosts);
        }

        public ActionResult HighestPosts()
        {
            var lastestPosts = Task.Run(() => _postService.GetMostViewPostsAsync(5)).Result;
            ViewBag.PartialViewTitle = "Highest Posts";
            return PartialView("_ListPost", lastestPosts);
        }

        public async Task<ActionResult> Details(int year, int month, string urlSlug)
        {
            var post = await _postService.FindPostAsync(year, month, urlSlug);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostTitle = post.Title;
            ViewBag.PublishedDate = ConvertTimePublished(post.PublishedDate);
            return View(post);
        }

        public string ConvertTimePublished(DateTime publishedDate)
        {
            const int second = 1;
            const int minute = 60 * second;
            const int hour = 60 * minute;
            const int day = 24 * hour;
            const int month = 30 * day;

            var time = new TimeSpan(DateTime.Now.Ticks - publishedDate.Ticks);
            double interval = Math.Abs(time.TotalSeconds);

            if (interval < 1 * minute)
            {
                return time.Seconds == 1 ? "one second ago" : time.Seconds + " seconds ago";
            }

            if (interval < 59 * minute)
            {
                return time.Minutes == 1 ? "one minute ago" : time.Minutes + " minutes ago";
            }

            if (interval < 24 * hour)
            {
                return time.Hours == 1 ? "an hour ago" : time.Hours + " hours ago";
            }

            if (interval < 30 * day)
            {
                return time.Days == 1 ? "one day ago" : time.Days + " days ago";
            }

            if (interval < 12 * month)
            {
                int months = Convert.ToInt32(Math.Floor((double)time.Days / 30));
                return months == 1 ? "one month ago" : months + " months ago";
            }
            else
            {
                int years = Convert.ToInt32(Math.Floor((double)time.Days / 365));
                return years == 1 ? "one year ago" : years + " years ago";
            }
        }

        public async Task<ActionResult> Comment(CommentCreateViewModel commentCreateViewModel)
        {
            var comment = new Comment()
            {
                Id = Guid.NewGuid(),
                Name = commentCreateViewModel.Name,
                Email = commentCreateViewModel.Email,
                CommentHeader = commentCreateViewModel.CommentHeader,
                CommentText = commentCreateViewModel.CommentText,
                PostId = commentCreateViewModel.PostId
            };
            var result = await _commentService.AddAsync(comment);
            if (result < 0)
            {
                return Json(new { errorMess = "Create comment failed" });
            }
            var commentViewModel = new CommentViewModel()
            {
                Id = comment.Id,
                Name = commentCreateViewModel.Name,
                Email = commentCreateViewModel.Email,
                CommentHeader = commentCreateViewModel.CommentHeader,
                CommentText = commentCreateViewModel.CommentText,
                PostId = commentCreateViewModel.PostId,
                CommentTime = comment.CommentTime.ToString("MMM dd yyyy")
            };
            return Json(commentViewModel);
        }
    }
}

src/FA.JustBlog/FA.JustBlog.WebMVC/Controllers/TagsController.cs
using FA.JustBlog.Services;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FA.JustBlog.WebMVC.Controllers
{
    public class TagsController : Controller
    {
        private readonly ITagService _tagServices;
        private readonly IPostService _postServices;

        public TagsController(ITagService tagServices, IPostService postServices)
        {
            _tagServices = tagServices;
            _postServices = postServices;
        }

        public async Task<ActionResult> Details(string urlSlug)
        {
            var tag = await _tagServices.GetTagByUrlSlugAsync(urlSlug);
            var posts = await _postServices.GetPostsByTagAsync(tag.Id);
            ViewBag.TagName = tag.Name;
            return View(posts);
        }

        public ActionResult PopularTags()
        {
            var popularTags = Task.Run(() => _tagServices.GetPopularTags()).Result;
            return PartialView("_PopularTags", popularTags);
        }
    }
}

src/FA.JustBlog/FA.JustBlog.WebMVC/Views/Shared/_AboutMe.cshtml
<aside class="single_sidebar_widget author_widget">
    <img class="author_img rounded-circle" src="~/assets/img/blog/c2.jpg" alt="author">
    <h4>Truonglt4</h4>
    <p>Senior blog writer</p>
    <div class="social_icon">
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
        <a href="#"><i class="fa fa-github"></i></a>
        <a href="#"><i class="fa fa-behance"></i></a>
    </div>
    <p>Boot camps have its supporters andit sdetractors. Some people do not understand why you should have to spend money on boot camp when you can get. Boot camps have itssuppor ters andits detractors.</p>
    <div class="br"></div>
</aside>

src/FA.JustBlog/FA.JustBlog.WebMVC/Views/Shared/_Footer.cshtml
@*<footer class="bg-light text-center text-lg-start mt-4">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
            &copy; @DateTime.Now.Year - Just Blog
        </div>
        <div class="">
            <a class="nav-link" href="@Url.Action("About", "Home", new { area = "" })">About</a>
        </div>
        <div class="">
            <a class="nav-link" href="@Url.Action("Contact", "Home", new { area = "" })">Contact</a>
        </div>

    </footer>*@
<footer class="footer-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-3  col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <a class="footer_title" href="@Url.Action("About", "Home", new { area = "" })">About</a>
                    <p>Click title go to about me</p>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6">
                <div class="single-footer-widget">
                    <a class="footer_title" href="@Url.Action("Contact", "Home", new { area = "" })">Contact</a>
                    <p>Click title go to contact</p>
                    <div id="mc_embed_signup">
                        <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
                            <div class="input-group d-flex flex-row">
                                <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
                                <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>
                            </div>
                            <div class="mt-10 info"></div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="single-footer-widget instafeed">
                    <h6 class="footer_title">Instagram Feed</h6>
                    <ul class="list instafeed d-flex flex-wrap">
                        <li><img src="~/App_Themes/fantom/img/instagram/Image-01.jpg" alt=""></li>
                        <li><img src="~/App_Themes/fantom/img/instagram/Image-02.jpg" alt=""></li>
                        <li><img src="~/App_Themes/fantom/img/instagram/Image-03.jpg" alt=""></li>
                        <li><img src="~/App_Themes/fantom/img/instagram/Image-04.jpg" alt=""></li>
                        <li><img src="~/App_Themes/fantom/img/instagram/Image-05.jpg" alt=""></li>
                        <li><img src="~/App_Themes/fantom/img/instagram/Image-06.jpg" alt=""></li>
                        <li><img src="~/App_Themes/fantom/img/instagram/Image-07.jpg" alt=""></li>
                        <li><img src="~/App_Themes/fantom/img/instagram/Image-08.jpg" alt=""></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-2 col-md-6 col-sm-6">
                <div class="single-footer-widget f_social_wd">
                    <h6 class="footer_title">Follow Us</h6>
                    <p>Let us be social</p>
                    <div class="f_social">
                        <a href="https://www.facebook.com/"><i class="fa fa-facebook"></i></a>
                        <a href="https://www.facebook.com/"><i class="fa fa-twitter"></i></a>
                        <a href="https://www.facebook.com/"><i class="fa fa-dribbble"></i></a>
                        <a href="https://www.facebook.com/"><i class="fa fa-behance"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="row footer-bottom d-flex justify-content-between align-items-center">
            <p class="col-lg-12 footer-text text-center">
                Copyright &copy;
                <script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib and Truonglt4 use it</a>
        </div>
    </div>
</footer>

src/FA.JustBlog/FA.JustBlog.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @*@Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")*@
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="~/App_Themes/fantom/css/bootstrap.css">
    <link rel="stylesheet" href="~/App_Themes/fantom/vendors/linericon/style.css">
    <link rel="stylesheet" href="~/App_Themes/fantom/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/App_Themes/fantom/vendors/owl-carousel/owl.carousel.min.css">
    <link rel="stylesheet" href="~/App_Themes/fantom/vendors/lightbox/simpleLightbox.css">
    <link rel="stylesheet" href="~/App_Themes/fantom/vendors/nice-select/css/nice-select.css">
    <link rel="stylesheet" href="~/App_Themes/fantom/vendors/animate-css/animate.css">
    <link rel="stylesheet" href="~/App_Themes/fantom/vendors/jquery-ui/jquery-ui.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Style+Script&display=swap" rel="stylesheet">
    <!-- main css -->
    <link rel="stylesheet" href="~/App_Themes/fantom/css/style.css">
    <link rel="stylesheet" href="~/App_Themes/fantom/css/responsive.css">

</head>
<body>
    <header class="header_area" style="position: static;">
        <div class="logo_part" style="margin-top:10px">
            <div class="container">
                <a class="logo" href="@Url.Action("Index", "Home", new { area = "" })" style="font-size: 80px;font-family: 'Style Script', cursive";>Just Blog</a>
            </div>
        </div>
        <div class="main_menu">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container">
                    @*Brand and toggle get grouped for better mobile display*@
                    <a class="navbar-brand logo_h" href="@Url.Action("Index", "Home", new { area = "" })" style="font-size: 30px;font-family:open-sans, sans-serif">Just Blog</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="@Url.Action("Index", "Home", new { area = "" })">Home <span class="sr-only">(current)</span></a>
                            </li>
                            @Html.Action("Menu", "Home", new { area = ""})

                            @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Identity Dashboard
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="@Url.Action("Index", "UsersAdmin", new { area = "Identity" })">Users Admin</a>
                                        <a class="dropdown-item" href="@Url.Action("Index", "RolesAdmin", new { area = "Identity" })">Roles Admin</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="@Url.Action("Index", "Manage", new { area = "" })">Manager</a>
                                    </div>
                                </li>

                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Admin Dashboard
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <a class="dropdown-item" href="@Url.Action("Index","CategoryManagement", new { area = "admin"})">Category Management</a>
                                        <a class="dropdown-item" href="@Url.Action("Index", "PostManagement", new { area = "admin"})">Post Management</a>
                                        <a class="dropdown-item" href="@Url.Action("Index", "TagManagement", new { area = "admin"})">Tag Management</a>
                                        <div class="dropdown-divider"></div>
                                        <a class="dropdown-item" href="#">Dashboard</a>
                                    </div>
                                </li>
                            }
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </nav>
        </div>
    </header>
    <div style="margin-top:0">

        @RenderBody()

        @Html.Partial("_Footer")
    </div>


    @*<footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/fontawesome.min.js" integrity="sha512-KCwrxBJebca0PPOaHELfqGtqkUlFUCuqCnmtydvBSTnJrBirJ55hRG5xcP4R9Rdx9Fz9IF3Yw6Rx40uhuAHR8Q==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    @RenderSection("scripts", required: false)
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="~/App_Themes/fantom/js/popper.js"></script>
    <script src="~/App_Themes/fantom/js/stellar.js"></script>
    <script src="~/App_Themes/fantom/vendors/lightbox/simpleLightbox.min.js"></script>
    <script src="~/App_Themes/fantom/vendors/nice-select/js/jquery.nice-select.min.js"></script>
    <script src="~/App_Themes/fantom/vendors/isotope/imagesloaded.pkgd.min.js"></script>
    <script src="~/App_Themes/fantom/vendors/isotope/isotope-min.js"></script>
    <script src="~/App_Themes/fantom/vendors/owl-carousel/owl.carousel.min.js"></script>
    <script src="~/App_Themes/fantom/vendors/jquery-ui/jquery-ui.js"></script>
    <script src="~/App_Themes/fantom/js/jquery.ajaxchimp.min.js"></script>
    <script src="~/App_Themes/fantom/js/mail-script.js"></script>
    <script src="~/App_Themes/fantom/js/theme.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

</body>
</html>

src/FA.JustBlog/FA.JustBlog.WebMVC/Views/Shared/_PartialFooter.cshtml
<footer class="bg-light text-center text-lg-start mt-4">
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        &copy; @DateTime.Now.Year - Just Blog
    </div>
</footer>

src/FA.JustBlog/FA.JustBlog.WebMVC/Views/Shared/_PostOverview.cshtml
<article class="blog_style1 shadow-card">
    <div class="blog_img">
        <img class="img-fluid" src="~/assets/img/home-blog/@Model.ImageUrl" alt="">
    </div>
    <div class="blog_text">
        <div class="blog_text_inner">
            <a class="cat" href="@Url.Action("Details", "Categories", new { urlSlug = Model.Category.UrlSlug })">@Model.Category.Name</a>
            <a href="@Url.Action("Details", "Posts", new { year = Model.PublishedDate.Year, month = Model.PublishedDate.Month.ToString("D2"), urlSlug = Model.UrlSlug})"><h4>@Model.Title</h4></a>
            
            <p>@Model.ShortDescription</p>
            <div class="date">
                <a href="#"><i class="fa fa-calendar" aria-hidden="true"></i> @Model.PublishedDate.ToString("dd MMM yyyy")</a>
                <a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> @Model.Comments.Count</a>
            </div>
        </div>
    </div>
</article>

src/FA.JustBlog/FA.JustBlog.WebMVC/Views/Shared/_RightMenu.cshtml
<div class="blog_right_sidebar">
    @Html.Partial("_AboutMe")
    @Html.Action("LastestPosts", "Posts")
    <hr />
    @Html.Action("MostViewPosts", "Posts")
    <hr />
    @Html.Action("HighestPosts", "Posts")
    <hr />
    @Html.Action("CategoryRightMenu", "Categories")
    <hr />
    @Html.Action("PopularTags", "Tags")
    <hr />
</div>