src/FA.JustBlog/FA.JustBlog.WebMVC/Areas/Admin/Controllers/PostManagementController.cs
using FA.JustBlog.Models.Common;
using FA.JustBlog.Services;
using FA.JustBlog.WebMVC.Areas.Admin.ViewModels;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FA.JustBlog.WebMVC.Areas.Admin.Controllers
{
    [Authorize]
    public class PostManagementController : Controller
    {
        private readonly IPostService _postServices;
        private readonly ICategoryService _categoryServices;
        private readonly ITagService _tagServices;

        public PostManagementController(IPostService postServices,
            ICategoryService categoryServices,
            ITagService tagServices)
        {
            _postServices = postServices;
            _categoryServices = categoryServices;
            _tagServices = tagServices;
        }

        
        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string searchString,
            int? pageIndex = 1, int pageSize = 2)
        {
            ViewData["CurrentPageSize"] = pageSize;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["TitleSortParm"] = string.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewData["UrlSlugSortParm"] = sortOrder == "UrlSlug" ? "urlSlug_desc" : "UrlSlug";
            ViewData["ViewsCountSortParm"] = sortOrder == "ViewsCount" ? "viewsCount_desc" : "ViewsCount";
            ViewData["PublishedSortParm"] = sortOrder == "Published" ? "published_desc" : "Published";
            ViewData["PublishedDateSortParm"] = sortOrder == "PublishedDate" ? "publishedDate_desc" : "PublishedDate";
            ViewData["UpdatedAtSortParm"] = sortOrder == "UpdatedAt" ? "updatedAt_desc" : "UpdatedAt";

            if (searchString != null)
            {
                pageIndex = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            // x => x.Name.Contains(searchString)
            Expression<Func<Post, bool>> filter = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = p => p.Title.Contains(searchString) || p.ShortDescription.Contains(searchString);
            }

            // q => q.OrderByDescending(c => c.Name)
            Func<IQueryable<Post>, IOrderedQueryable<Post>> orderBy = null;

            switch (sortOrder)
            {
                case "title_desc":
                    orderBy = q => q.OrderByDescending(c => c.Title);
                    break;
                case "UrlSlug":
                    orderBy = q => q.OrderBy(c => c.UrlSlug);
                    break;
                case "urlSlug_desc":
                    orderBy = q => q.OrderByDescending(c => c.UrlSlug);
                    break;
                case "ViewsCount":
                    orderBy = q => q.OrderBy(c => c.ViewCount);
                    break;
                case "viewsCount_desc":
                    orderBy = q => q.OrderByDescending(c => c.ViewCount);
                    break;
                case "Published":
                    orderBy = q => q.OrderBy(c => c.Published);
                    break;
                case "published_desc":
                    orderBy = q => q.OrderByDescending(c => c.Published);
                    break;
                case "PublishedDate":
                    orderBy = q => q.OrderBy(c => c.PublishedDate);
                    break;
                case "publishedDate_desc":
                    orderBy = q => q.OrderByDescending(c => c.PublishedDate);
                    break;
                case "UpdatedAt":
                    orderBy = q => q.OrderBy(c => c.UpdatedAt);
                    break;
                case "updatedAt_desc":
                    orderBy = q => q.OrderByDescending(c => c.UpdatedAt);
                    break;
                default:
                    orderBy = q => q.OrderBy(c => c.Title);
                    break;
            }

            var posts = await _postServices.GetAsync(filter: filter, orderBy: orderBy, pageIndex: pageIndex ?? 1, pageSize: pageSize);

            return View(posts);
        }


        // GET: Admin/PostManagement/Create
        public ActionResult Create()
        {
            ViewBag.Categories = new SelectList(_categoryServices.GetAll(), "Id", "Name");
            var postViewModel = new PostViewModel();
            postViewModel.Tags = _tagServices.GetAll().Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.Name });
            return View(postViewModel);
        }

        // POST: Admin/PostManagement/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Create(PostViewModel postViewModel)
        {
            if (ModelState.IsValid)
            {
                var post = new Post
                {
                    Id = Guid.NewGuid(),
                    Title = postViewModel.Title,
                    UrlSlug = postViewModel.UrlSlug,
                    ShortDescription = postViewModel.ShortDescription,
                    ImageUrl = postViewModel.ImageUrl,
                    PostContent = postViewModel.PostContent,
                    Published = postViewModel.Published,
                    CategoryId = postViewModel.CategoryId,
                    ViewCount = postViewModel.ViewCount,
                    RateCount = postViewModel.RateCount,
                    TotalRate = postViewModel.TotalRate,
                    ImageSlider = postViewModel.ImageSlider,
                    
                    Tags = await GetSelectedTagFromIds(postViewModel.SelectedTagIds)
                };
                var result =  _postServices.Add(post);

                return RedirectToAction("Index");
            }

            ViewBag.Categories = new SelectList(await _categoryServices.GetAllAsync(), "Id", "Name", postViewModel.CategoryId);
            postViewModel.Tags = _tagServices.GetAll().Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.Name });
            return View(postViewModel);
        }

        private async Task<ICollection<Tag>> GetSelectedTagFromIds(IEnumerable<Guid> selectedTagIds)
        {
            var tags = new List<Tag>();
            if (selectedTagIds == null)
            {
                return tags;
            }
            var tagEntities = await _tagServices.GetAllAsync();

            foreach (var item in tagEntities)
            {
                if (selectedTagIds.Any(x => x == item.Id))
                {
                    tags.Add(item);
                }
            }
            return tags;
        }

        // GET: Admin/PostManagement/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {

            var post = await _postServices.GetByIdAsync((Guid)id);
            var postViewModel = new PostViewModel()
            {
                Id = post.Id,
                Title = post.Title,
                UrlSlug = post.UrlSlug,
                ShortDescription = post.ShortDescription,
                ImageUrl = post.ImageUrl,
                PostContent = post.PostContent,
                Published = post.Published,
                CategoryId = post.CategoryId,
                ViewCount = post.ViewCount,
                RateCount = post.RateCount,
                TotalRate = post.TotalRate,
                ImageSlider = post.ImageSlider,
                SelectedTagIds = post.Tags.Select(x => x.Id )
            };
            ViewBag.Categories = new SelectList(_categoryServices.GetAll(), "Id", "Name", postViewModel.CategoryId);
            postViewModel.Tags = _tagServices.GetAll().Select(t => new SelectListItem { Value = t.Id.ToString(), Text = t.Name });
            ViewBag.TagList = _tagServices.GetAll();
            return View(postViewModel);
        }

        // POST: Admin/PostManagement/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(PostViewModel postViewModel)
        {
            if (ModelState.IsValid)
            {
                var post = await _postServices.GetByIdAsync(postViewModel.Id);
                if (post == null)
                {
                    return HttpNotFound();
                }
                post.Title = postViewModel.Title;
                post.UrlSlug = postViewModel.UrlSlug;
                post.ShortDescription = postViewModel.ShortDescription;
                post.ImageUrl = postViewModel.ImageUrl;
                post.PostContent = postViewModel.PostContent;
                post.Published = postViewModel.Published;
                post.CategoryId = postViewModel.CategoryId;
                post.ViewCount = postViewModel.ViewCount;
                post.RateCount = postViewModel.RateCount;
                post.TotalRate = postViewModel.TotalRate;
                post.ImageSlider = postViewModel.ImageSlider;
                await UpdateSelectedTagFromIds(postViewModel.SelectedTagIds, post);

                var result = await _postServices.UpdateAsync(post);
                if (result)
                {
                    TempData["Message"] = "Update successful!";
                }
                else
                {
                    TempData["Message"] = "Update failed!";

                }
                return RedirectToAction("Index");
            }

src/FA.JustBlog/FA.JustBlog.WebMVC/Areas/Admin/Views/PostManagement/Create.cshtml
@model PostViewModel

@{
    ViewBag.Title = "Create Post";
}

<h2 class="text-center">Create new post</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="row">
        <div class="col-md-12">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", id = "input-title"  } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control",@readonly = true , id ="input-urlslug"} })
                @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.ImageSlider, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.ImageSlider, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageSlider, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.ViewCount, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.ViewCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.RateCount, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.RateCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.TotalRate, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.TotalRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.DropDownListFor(model => model.CategoryId, new SelectList(ViewBag.Categories, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            <label class="control-label" for="Tag">Tags</label>
            <div class="">
                @Html.ListBoxFor(model => model.SelectedTagIds, Model.Tags, new { @class = "select-tag-multiple" })
            </div>
        </div>


        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.PostContent, htmlAttributes: new { @class = "control-label" })
            <div class="">
                <textarea class="form-control" name="PostContent" id="ckeditor"></textarea>
                @Html.ValidationMessageFor(model => model.PostContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label" })
            <div>
                <div class="checkbox">
                    @Html.EditorFor(model => model.Published)
                    @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group col-md-6">
            <button type="submit" class="btn btn-info">
                Create
            </button>
            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-secondary ml-2" })
        </div>
    </div>
}

@section scripts {
    <script src="~/Assets/js/ckeditor/ckeditor.js"></script>
    <script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
    <script src="~/assets/js/select-muitiple.js"></script>
    <script src="~/assets/js/convert-urlslug.js"></script>
} 

src/FA.JustBlog/FA.JustBlog.WebMVC/Areas/Admin/Views/PostManagement/Edit.cshtml
@model PostViewModel

@{
    ViewBag.Title = "Edit Post";
}

<h2 class="text-center">Edit: @Model.Title</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.Id)
    <div class="row">
        <div class="col-md-12">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", id = "input-title" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control", @readonly = true, id="input-urlslug" } })
                @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.ImageUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.ImageSlider, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.ImageSlider, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ImageSlider, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.ViewCount, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.ViewCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ViewCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.RateCount, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.RateCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RateCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.TotalRate, htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.EditorFor(model => model.TotalRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.CategoryId, "CategoryId", htmlAttributes: new { @class = "control-label" })
            <div>
                @Html.DropDownListFor(model => model.CategoryId, new SelectList(ViewBag.Categories, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            <label class="control-label" for="Tag">Tags</label>
            <div class="">
                @Html.ListBoxFor(model => model.SelectedTagIds, Model.Tags, new { @class = "select-tag-multiple" })
            </div>
        </div>


        <div class="form-group col-md-12">
            @Html.LabelFor(model => model.PostContent, htmlAttributes: new { @class = "control-label" })
            <div class="">
                <textarea class="form-control" name="PostContent" id="ckeditor">@Model.PostContent</textarea>
                @Html.ValidationMessageFor(model => model.PostContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group col-md-6">
            @Html.LabelFor(model => model.Published, htmlAttributes: new { @class = "control-label" })
            <div>
                <div class="checkbox">
                    @Html.EditorFor(model => model.Published)
                    @Html.ValidationMessageFor(model => model.Published, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group col-md-6">
            <button type="submit" class="btn btn-info">
                Edit
            </button>
            @Html.ActionLink("Back", "Index", null, new { @class = "btn btn-secondary ml-2" })
        </div>
    </div>
}

@section scripts {
    <script src="~/Assets/js/ckeditor/ckeditor.js"></script>
    <script src="~/Assets/js/ckeditor/ckeditorconfig.js"></script>
    <script src="~/assets/js/select-muitiple.js">
        
    </script>
    <script src="~/assets/js/convert-urlslug.js">

    </script>
} 

src/FA.JustBlog/FA.JustBlog.WebMVC/Areas/Admin/Views/PostManagement/Index.cshtml
@model Paginated<Post>

@{
    ViewBag.Title = "Post Management";
}

<h2 class="text-center">Post Management</h2>
<h3>@TempData["Message"]</h3>
<hr />
<div>
    <a href="@Url.Action("Create", "PostManagement")" class="btn btn-primary float-left"><span class="fas fa-plus-square"></span></a>

    <form action="@Url.Action("Index", "PostManagement")" method="get" class="form-inline float-right">
        <div class="form-group mx-sm-3 mb-2">
            <input type="text" class="form-control mr-3" id="inputSearch" name="SearchString" value="@ViewData["currentFilter"]" placeholder="Input....">
            <button type="submit" class=" form-control btn btn-primary">
                <i class="fas fa-search"></i>
            </button>
            <a href="@Url.Action("Index")" class="btn btn-default">
                <i class="fas fa-redo"></i>
            </a>
        </div>
    </form>
</div>

@if (!Model.Any())
{
    <h3 class="text-center">Don't have a category yet.</h3>
}
else
{
    <table class="table table-condensed table-bordered">
        <tr class="d-flex">
            <th class="col-md-2">
                <a href="@Url.Action("Index", "PostManagement", new { sortOrder = ViewData["TitleSortParm"], currentFilter = ViewData["CurrentFilter"] })">Title</a>
            </th>
            <th class="col-md-2">
                <a href="@Url.Action("Index", "PostManagement", new { sortOrder = ViewData["UrlSlugSortParm"], currentFilter = ViewData["CurrentFilter"] })">Url Slug</a>
            </th>
            <th class="col-md-2">
                <a href="@Url.Action("Index", "PostManagement", new { sortOrder = ViewData["PublishedSortParm"], currentFilter = ViewData["CurrentFilter"] })">Published</a>
            </th>
            <th class="col-md-2">
                <a href="@Url.Action("Index", "PostManagement", new { sortOrder = ViewData["PublishedDateSortParm"], currentFilter = ViewData["CurrentFilter"] })">Published Date</a>
            </th>
            <th class="col-md-2">
                <a href="@Url.Action("Index", "PostManagement", new { sortOrder = ViewData["UpdatedAtSortParm"], currentFilter = ViewData["CurrentFilter"] })">Updated At</a>
            </th>
            <th class="col-md-2">Manage</th>
        </tr>

        @foreach (var post in Model)
        {
            <tr class="d-flex">
                <td class="col-md-2">
                    <a href="@Url.Action("Details", new { id = post.Id})">
                        @post.Title
                    </a>
                </td>
                <td class="col-md-2">
                    @post.UrlSlug
                </td>
                <td class="col-md-2">
                    @post.Published
                </td>
                <td class="col-md-2">
                    @post.PublishedDate
                </td>
                <td class="col-md-2">
                    @post.UpdatedAt
                </td>
                <td class="col-md-2">
                    <form action="@Url.Action("Delete", "PostManagement", new{ id = post.Id })" method="post">
                        <a href="@Url.Action("Edit", "PostManagement", new { id = post.Id})" class="btn btn-primary">Edit</a>
                        <button type="submit" onclick="return confirm('Are you sure to delete this post?');" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        }
    </table>

    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            @{
                var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                ViewBag.PageRange = 3;
            }
            <li class="page-item">
                <a href="@Url.Action("Index", "PostManagement", new { sortOrder=ViewData["CurrentSort"], pageIndex=1, currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @prevDisabled"><<</a>
            <li class="page-item">
                <a href="@Url.Action("Index", "PostManagement", new { sortOrder=ViewData["CurrentSort"], pageIndex=(Model.PageIndex - 1 <= 0 ? 1 : Model.PageIndex - 1), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @prevDisabled"><</a>
            </li>
            @for (int i = 1; i <= Model.TotalPages; i++)
            {
                if (i >= Model.PageIndex - ViewBag.PageRange && i <= Model.PageIndex + ViewBag.PageRange)
                {
                    <li class="page-item">
                        <a class="@(i==Model.PageIndex ? "Current" : "") page-link"
                           href="@Url.Action("Index", "PostManagement", new { sortOrder=ViewData["CurrentSort"], pageIndex=i, currentFilter=ViewData["CurrentFilter"] })">@i</a>
                    </li>
                }
            }
            <li class="page-item">
                <a href="@Url.Action("Index", "PostManagement", new { sortOrder=ViewData["CurrentSort"], pageIndex=(Model.PageIndex + 1 > Model.TotalPages ? Model.TotalPages : Model.PageIndex + 1), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @nextDisabled">></a>
            <li class="page-item">
                <a href="@Url.Action("Index", "PostManagement", new { sortOrder=ViewData["CurrentSort"], pageIndex=(Model.TotalPages), currentFilter=ViewData["CurrentFilter"] })"
                   class="btn page-link @nextDisabled">>></a>
        </ul>
    </nav>
}